FROM node:18-alpine

# Install dependencies untuk Puppeteer
RUN apk add --no-cache \
  chromium \
  noto-sans

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3000

CMD ["npm", "start"]